#include <catch.hpp>
#include "../src/TwoBit/err/Exception.hpp"

/*
TEST_CASE("Basic tests for Exception", "[void Exception (std::string& funcName,std::string& s)]" ){
  SECTION("GIVE SECTION NAME"){
      YOUR CODE GOES HERE
        NORMALLY END WITH A REQUIRE STATEMENT e.g.
        REQUIRE(TESTVAL1 == YOURVAL);
  }
}
*/

/*
TEST_CASE("Basic tests for Exception", "[void Exception (std::string& s)]" ){
  SECTION("GIVE SECTION NAME"){
      YOUR CODE GOES HERE
        NORMALLY END WITH A REQUIRE STATEMENT e.g.
        REQUIRE(TESTVAL1 == YOURVAL);
  }
}
*/

/*
TEST_CASE("Basic tests for Exception", "[void Exception ()]" ){
  SECTION("GIVE SECTION NAME"){
      YOUR CODE GOES HERE
        NORMALLY END WITH A REQUIRE STATEMENT e.g.
        REQUIRE(TESTVAL1 == YOURVAL);
  }
}
*/

/*
TEST_CASE("Basic tests for what", "[const char * what ()]" ){
  SECTION("GIVE SECTION NAME"){
      YOUR CODE GOES HERE
        NORMALLY END WITH A REQUIRE STATEMENT e.g.
        REQUIRE(TESTVAL1 == YOURVAL);
  }
}
*/
